const number1 = 8;
const number2 = 24;
const number3 = number1 * number2;
console.log('value of product:', number3);
console.log('typeof product:', typeof number3);
const charge = 24;
const payment = 8;
const amountRemaining = charge - payment;
console.log('value of amountRemaining:', amountRemaining);
console.log('typeof amountRemaining:', typeof amountRemaining);
const tests = 95;
const assignments = 100;
const final = 78;
const grade = (tests + assignments + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Paxton';
const lastName = 'Rosenberg';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const numberOfSoldiers = 500;
const isSparta = numberOfSoldiers === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const nickname = fullName + ' ' + 'is the GOAT';
console.log('value of nickname:', nickname);
console.log('typeof nickname:', typeof nickname);
